uint8_t basic_menu(char title[], char *options[], uint8_t quit_option);
uint8_t scroll_menu(char title[], char *options[], uint8_t num_options);
uint24_t center_cursor_x(char string[]);
void main_menu(void);
uint8_t difficulty_select(void);
void about_screen(void);
void pack_select(void);
void level_select(char *pack_name);
void wait_for_key_press(void);
void wait_for_key_release(void);